### PR TITLE
Fixed spelling

### PR DESCRIPTION
**Pull request by beono**
Hi,

Some minor fixes in the comments

### CODE REVIEW

**Review by zerospiel — APPROVED** [review]
LGTM

**Comment by bullgare** [comment]
TBH, I don't know why we even need these lines.
Because of them any modifications to the files are rendered collapsed on Github. I try to remove it all the time anyway.

**Comment by zerospiel** [comment]
Hi, @bullgare 

It makes sense, do you think that it's a better way to have comments on RPCs stubs rather than the first line? The second one looks good, IMO. I mean that stub can be generated like:

```golang
// source: github.com/user/repo/api/v1/file.proto

package foobarpkg

import (
	"context"

	"github.com/pkg/errors"
	desc "github.com/user/repo/pkg/v1/foobar"
)

// FooBar should be implemented and commented well.
func (i *Implementation) FooBar(ctx context.Context, req *desc.Req) (*desc.Resp, error) {
	return nil, errors.New("FooBar not implemented")
}
```

**Comment by bullgare** [comment]
I like your example.
I'd vote for this approach.

**Comment by beono** [comment]
Maybe these lines are there to give someone a clue about the tool that was used to generate the file. Just in case a new project member is inspecting the application code.

**Comment by bullgare** [comment]
We could at least change it to something that is not treated as a special
case by IDE and GitHub/Gitlab

**Comment by utrack** [comment]
Thanks! 

True, I guess we could have different headers for implementation stubs.

**Pull request merged**
