### PR TITLE
Add test reproducing panic during marshaling response

### PR DESCRIPTION
**Pull request by doroginin**

### CODE REVIEW

**Comment by utrack** [comment]
This way, we're buffering the whole response in memory instead of dumping it right away - that can eat quite a lot of memory and CPU for byte allocations. I'm not sure which panic that'll fix except if a writer is nil; can you show me the stacktrace, please?

**Comment by doroginin** [comment]
for example this:
```
panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage [recovered]
	panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage

goroutine 8 [running]:
testing.tRunner.func1(0xc000186200)
	/usr/local/go/src/testing/testing.go:792 +0x387
panic(0x967a20, 0xc000488150)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalValue(0xe986a0, 0xc0004dfb90, 0xc000226240, 0xa020e0, 0xc0004ccbe0, 0x199, 0x0, 0x0, 0xc0000505d8, 0xc000226240)
	/home/dd/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:554 +0xbbd
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalField(0xe986a0, 0xc0004dfb90, 0xc000226240, 0xa020e0, 0xc0004ccbe0, 0x199, 0x0, 0x0, 0x0, 0xc000468810)
	/home/dd/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:475 +0x107
github.com/golang/protobuf/jsonpb.(*Marshaler).marshalObject(0xe986a0, 0xc0004dfb90, 0xaa92c0, 0xc0004ccbe0, 0x0, 0x0, 0x0, 0x0, 0x96afc0, 0x8e7f29)
	/home/dd/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:333 +0x4fe
github.com/golang/protobuf/jsonpb.(*Marshaler).Marshal(0xe986a0, 0xaa2c40, 0xc00017e1c0, 0xaa92c0, 0xc0004ccbe0, 0xe99501, 0xda3a28b4479c7954)
	/home/dd/go/pkg/mod/github.com/golang/protobuf@v1.2.0/jsonpb/jsonpb.go:138 +0x1ad
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).marshalTo(0xe986a0, 0xaa2c40, 0xc00017e1c0, 0x9bdec0, 0xc0004ccbe0, 0x20, 0x997e80)
	/home/dd/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.0/runtime/marshal_jsonpb.go:50 +0x110
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).NewEncoder.func1(0x9bdec0, 0xc0004ccbe0, 0x997e80, 0xc0004ccc40)
	/home/dd/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.0/runtime/marshal_jsonpb.go:115 +0x50
github.com/grpc-ecosystem/grpc-gateway/runtime.EncoderFunc.Encode(0xc0004ccc40, 0x9bdec0, 0xc0004ccbe0, 0xaa3da0, 0xc0004ccc40)
	/home/dd/go/pkg/mod/github.com/grpc-ecosystem/grpc-gateway@v1.5.0/runtime/marshaler.go:42 +0x3a
github.com/utrack/clay/v2/transport/httpruntime.MarshalerPbJSON.Marshal(0xe986a0, 0xe986e0, 0xe98720, 0xe97890, 0xaa2c40, 0xc00017e1c0, 0x9bdec0, 0xc0004ccbe0, 0x10, 0xc00036d4d8)
	/home/dd/data/Documents/dev/src/github.com/utrack/clay/transport/httpruntime/mjson.go:68 +0xb2
github.com/utrack/clay/integration/panic_in_response_marshaler/pb.(*Strings_httpClient).Echo(0xc0004dff30, 0xaaa180, 0xc00009e010, 0xc0004ccbe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/dd/data/Documents/dev/src/github.com/utrack/clay/integration/panic_in_response_marshaler/pb/strings.pb.goclay.go:179 +0x140
github.com/utrack/clay/integration/panic_in_response_marshaler.TestEcho(0xc000186200)
	/home/dd/data/Documents/dev/src/github.com/utrack/clay/integration/panic_in_response_marshaler/main_test.go:24 +0x1e3
testing.tRunner(0xc000186200, 0xa33378)
	/usr/local/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:878 +0x353
```

**Comment by utrack** [comment]
I'm not sure how adding an intermediate buffer would fix that. This is a problem b/c of golang/jsonpb that is used for gogo/jsonpb generated code, changing write destination won't fix anything.

**Comment by doroginin** [comment]
Changing write destination fixes ResponseWriter buffer, because now it can have broken json:
```
{"time_field":{"error":"recovered from panic: interface conversion: *time.Time is not proto.Message: missing method ProtoMessage"}
```
And even we will recover this panic we can't modify already written broken json.

**Comment by utrack** [comment]
Yeah, but it's a hack, not the root problem.

**Comment by doroginin** [comment]
Ok, i reverted this changes. Instead of this I added test reproducing panic problem, also `binding_with_different_types_post` test was added (the same as `binding_with_different_types` but for http POST and with WKT types)

**Comment by doroginin** [comment]
To prevent panic in case of using: `google.protobuf.Timestamp stdtime = 19 [(gogoproto.stdtime) = true, (gogoproto.nullable) = false];`
1) You should use `gogofast` protoc plugin or use `option (gogoproto.gogoproto_import) = true;` option in your proto.
2) If you would like to use `reflection.Register` for your service, you should also use this option in your proto: `option (gogoproto.goproto_registration) = true;`

**Pull request merged**
