### PR TITLE
Close notifier fix

### PR DESCRIPTION
**Pull request by makhov**
Build tag added to fix the error:
```
# github.com/utrack/clay/v2/server/middlewares/mwhttp
../../go/pkg/mod/github.com/utrack/clay/v2@v2.4.1/server/middlewares/mwhttp/closenotifier.go:7:9: undefined: middleware.CloseNotify
```

### CODE REVIEW

**Comment by utrack** [comment]
Thank you for your contribution! I'm not sure we want to support EOL'd versions of Go though - in fact, I've planned to remove pre-Go1.11 crutches related to `vgo`. Do you use Go pre-1.9 a lot?

**Comment by makhov** [comment]
No, we use go1.13 and we get the error, because `middleware.CloseNotify` was removed from `chi`. 
Please, notice that the build tag contains `!go1.9`. This means it won't be compiled from v1.9 and above.

**Comment by utrack** [comment]
Thank you for your contribution! 

I don't think that fixes the problem properly.
It seems like `gin/mw.CloseNotify` was removed in some recent version of `gin`, but currently `clay` uses an old version that still has it in code.

Since `CloseNotifier` is deprecated - I think it'd be a good idea to remove that middleware entirely (esp when current PR already does it for post-1.8 builds and leaves pre-1.9 broken when a recent version of `chi` is vendored).

Can you please remove the `CloseNotifier` from code entirely?

**Comment by makhov** [comment]
Done!

**Comment by makhov** [comment]
Thanks for merging! Could you create a new tag, please, to make it work with Go modules?

**Comment by utrack** [comment]
Sure - tagged v2.4.2.

**Pull request merged**
